env:
  browser: true
  es6: true
  node: true
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  # - react
  # - react-hooks
  - "@typescript-eslint/eslint-plugin"
  - "@typescript-eslint"
  - prettier
  - emotion
extends:
  - react-app
  # - standard
  - "plugin:prettier/recommended"
  - "prettier/react"
  - "prettier/@typescript-eslint"
  - "eslint:recommended"
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:@typescript-eslint/recommended"
settings:
  react:
    version: "detect"
rules: {
  '@typescript-eslint/explicit-function-return-type': 'off'
}
